### ISSUE TITLE
Its empty

### ISSUE THREAD

**Issue by ldrrp** [tomburtless/first-docker-repo#1]
lol hi

**Comment by tomburtless** [comment]
I'm just getting started on it man!

**Comment by tomburtless** [comment]
Haven't even used my github since I left the news haha

**Comment by ldrrp** [comment]
i havent made any repo's yet but ive been using it alot lately with my home nas setup, got like 17 containers running diff things

**Comment by tomburtless** [comment]
yeah I was talking to Andrew earlier and he suggested giving it a go.  I hadn't previously but I see it everywhere now and looking into it a bit more I can see why.

Also love that everything I had starred on here up until 15 minutes ago was like bootstrap 3 libraries from 7 years ago.

**Comment by ldrrp** [comment]
https://github.com/SiloCityLabs/docker-nas this my nas setup atm, basic so friends can use it. i keep the extra stuff seperate.

Also checkout portainer. shit is dope for a **simple** management interface.
